inclusao v1 provisionamento api gateway
Grupo-G03-4SOAT-FIAP/rms-iac pull request #18
Opened 2024-05-05 21:14 UTC by DiegoOLiveira-dev

Inclusão do modulo de provisionamento de api gateway

2024-05-05 21:17 UTC, anaplopes approved these changes

2024-05-05 21:42 UTC, dannevesdantas requested changes

2024-05-05 21:42 UTC, dannevesdantas commented on modules/api-gateway/main.tf
> +  ]
@DiegoOLiveira-dev quando finalizarmos o Tech Challenge, teremos 3 rotas: 
- `/catalogo` para a nova API de Catálogo de Produtos
- `/pedido` para a nova API de Pedidos
- `/pagamento` para a nova API de Pagamentos

Creio que já podemos deixar 3 rotas pré-criadas.

O endereço do Load Balancer da AWS referente a cada um dos services do k8s infelizmente só saberemos depois que for feito `apply` dos manifestos do K8s. Por hora acho que podemos deixar "https://exemplo.com/" sem problemas e depois substituímos pelo endereço real manualmente lá no Console da AWS, após fazer o `terraform apply`.

2024-05-05 21:42 UTC, dannevesdantas commented on modules/api-gateway/rotas/rotas_api.tf
> +
Conseguimos limpar essas linhas em branco no final do arquivo?

2024-05-05 21:42 UTC, dannevesdantas commented on modules/api-gateway/gateway/api_gateway.tf
> +
Conseguimos limpar essas linhas em branco no final do arquivo?

2024-05-05 21:42 UTC, dannevesdantas commented on modules/api-gateway/gateway/api_gateway.tf
> +# }
Boa @DiegoOLiveira-dev! Depois (em outra PR) vou linkar o Cognito aqui no seu módulo do API Gateway blz?

2024-05-06 23:25 UTC, dannevesdantas approved these changes

2024-05-06 23:25 UTC, merged